/* eslint-disable @next/next/no-html-link-for-pages */
import { registry } from "@/lib/registry";

export default async function Home() {
  const pack = await registry.get("@vxnus/siduri-basics", "0.1.0");
  if (!pack) throw new Error("catalog pack is missing");

  return <main>
    <nav className="site-nav" aria-label="Primary navigation"><a className="brand" href="/"><span className="brand-mark">E</span> knowledge hub</a><div className="nav-links"><a href="#catalog">Catalog</a><a href="#publish">Publish</a><a className="nav-button" href="#install">Use with Siduri</a></div></nav>
    <section className="hero" aria-labelledby="hero-title"><div className="hero-copy"><p className="eyebrow">Open knowledge infrastructure</p><h1 id="hero-title">Knowledge your companion can trust.</h1><p className="hero-lede">Discover versioned, cited knowledge packs built to install cleanly into Siduri.</p><div className="hero-actions"><a className="button button-primary" href="#catalog">Browse the catalog</a><a className="text-link" href="#publish">Publish a pack <span aria-hidden="true">↗</span></a></div></div><div className="hero-index" aria-label="Hub status"><div className="index-orbit"><span>01</span><i /></div><div className="index-note"><span>Currently indexed</span><strong>01 knowledge pack</strong><small>Revision-aware · cited · portable</small></div></div></section>
    <section className="catalog" id="catalog" aria-labelledby="catalog-title"><div className="section-heading"><div><p className="eyebrow">The first entry</p><h2 id="catalog-title">Start with something small.</h2></div><p>A tiny pack makes the whole path visible: publish, install, retrieve, cite.</p></div><article className="pack-card"><div className="pack-number">01</div><div className="pack-main"><div className="pack-title-row"><h3>{pack.id}</h3><span className="status"><i /> verified</span></div><p>{pack.description}</p><div className="pack-meta"><span>v{pack.version}</span><span>{pack.sources[0].title}</span><span>{pack.sources[0].license}</span></div></div><a className="pack-arrow" href="/packs/vxnus/siduri-basics" aria-label={`View ${pack.id} details`}>↗</a></article></section>
    <section className="install" id="install" aria-labelledby="install-title"><div><p className="eyebrow">From catalog to companion</p><h2 id="install-title">Install knowledge where it belongs.</h2><p>Siduri owns local installation and runtime state. The Hub makes the pack discoverable and distributable.</p></div><div className="install-code"><span className="code-label">LOCAL DEVELOPMENT</span><code><b>$</b> siduri create<br /><em>Knowledge pack path?</em> ./siduri-basics</code><span className="code-caption">The same contract later ships from the Hub.</span></div></section>
    <section className="publish" id="publish" aria-labelledby="publish-title"><p className="eyebrow">For publishers</p><h2 id="publish-title">Publish once. Let Siduri handle the rest.</h2><a className="button button-dark" href="mailto:hello@vxnuslabs.com">Read the pack guide <span aria-hidden="true">↗</span></a></section>
    <footer><span>© 2026 E Knowledge Hub</span><span>Protocol by <a href="https://github.com/vxnuslabs/e">@vxnus/e</a></span></footer>
  </main>;
}
