import { bigint, boolean, jsonb, pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";

export const publisherProjects = pgTable("publisher_projects", { id: uuid("id").defaultRandom().primaryKey(), ownerId: uuid("owner_id").notNull(), publisher: text("publisher").notNull(), name: text("name").notNull(), description: text("description"), visibility: text("visibility").notNull().default("private"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() });
export const publisherProfiles = pgTable("publisher_profiles", { userId: uuid("user_id").primaryKey(), username: text("username").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() });
export const publisherMembers = pgTable("publisher_members", { projectId: uuid("project_id").notNull(), userId: uuid("user_id").notNull(), role: text("role").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() });
export const publisherSources = pgTable("publisher_sources", { id: uuid("id").defaultRandom().primaryKey(), projectId: uuid("project_id").notNull(), sourceId: text("source_id").notNull(), title: text("title").notNull(), license: text("license").notNull(), uri: text("uri"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() });
export const publisherRevisions = pgTable("publisher_revisions", { id: uuid("id").defaultRandom().primaryKey(), projectId: uuid("project_id").notNull(), revisionId: text("revision_id").notNull(), manifest: jsonb("manifest").notNull(), checksum: text("checksum"), status: text("status").notNull().default("draft"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() });
export const publisherReleases = pgTable("publisher_releases", { id: uuid("id").defaultRandom().primaryKey(), projectId: uuid("project_id").notNull(), revisionId: uuid("revision_id").notNull(), packageId: text("package_id").notNull(), version: text("version").notNull(), status: text("status").notNull().default("published"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() });
export const publisherDistributions = pgTable("publisher_distributions", { id: uuid("id").defaultRandom().primaryKey(), releaseId: uuid("release_id").notNull(), kind: text("kind").notNull(), url: text("url").notNull(), checksum: text("checksum"), status: text("status").notNull().default("ready"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() });
export const publisherAuditEvents = pgTable("publisher_audit_events", { id: bigint("id", { mode: "number" }).generatedAlwaysAsIdentity().primaryKey(), projectId: uuid("project_id").notNull(), actorId: uuid("actor_id"), action: text("action").notNull(), metadata: jsonb("metadata").notNull().default({}), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() });
export const registryPacks = pgTable("registry_packs", { packageId: text("package_id").notNull(), name: text("name").notNull(), publisher: text("publisher").notNull(), version: text("version").notNull(), schemaVersion: text("schema_version").notNull(), description: text("description"), license: jsonb("license"), sources: jsonb("sources").notNull(), capabilities: jsonb("capabilities").notNull(), publisherId: uuid("publisher_id").notNull(), distribution: jsonb("distribution").notNull(), verified: boolean("verified").notNull().default(false), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() });
