import "server-only";
import { and, desc, eq } from "drizzle-orm";
import { getDatabase } from "@/db";
import { publisherDistributions, publisherProjects, publisherProfiles, publisherReleases, registryPacks } from "@/db/schema";

import type { KnowledgePackManifest } from "@vxnus/e";

export type PublisherProject = { id: string; publisher: string; name: string; description: string | null; visibility: "private" | "public"; manifest: Partial<KnowledgePackManifest> | null; created_at: string; updated_at: string };
export function isControlPlaneConfigured() { return Boolean(process.env.DATABASE_URL); }
export async function listPublisherProjects(ownerId: string): Promise<PublisherProject[]> { const rows = await getDatabase().select().from(publisherProjects).where(eq(publisherProjects.ownerId, ownerId)).orderBy(desc(publisherProjects.updatedAt)); return rows.map((row) => ({ id: row.id, publisher: row.publisher, name: row.name, description: row.description, visibility: row.visibility as "private" | "public", manifest: (row.manifest as Partial<KnowledgePackManifest>) || null, created_at: row.createdAt.toISOString(), updated_at: row.updatedAt.toISOString() })); }
export async function getPublisherProfile(userId: string) { const rows = await getDatabase().select({ username: publisherProfiles.username }).from(publisherProfiles).where(eq(publisherProfiles.userId, userId)).limit(1); return rows[0]; }
export async function getProjectByPublisher(publisher: string) { const rows = await getDatabase().select({ id: publisherProjects.id, name: publisherProjects.name, publisher: publisherProjects.publisher, description: publisherProjects.description, visibility: publisherProjects.visibility, manifest: publisherProjects.manifest }).from(publisherProjects).where(and(eq(publisherProjects.publisher, publisher), eq(publisherProjects.visibility, "public"))).limit(1); return rows[0]; }
export async function createPublisherProject(input: { ownerId: string; publisher: string; name: string; description?: string; visibility?: "private" | "public"; manifest?: Partial<KnowledgePackManifest> }) { const rows = await getDatabase().insert(publisherProjects).values({ ownerId: input.ownerId, publisher: input.publisher, name: input.name, description: input.description || null, visibility: input.visibility || "public", manifest: input.manifest || null }).returning(); return rows[0]; }
export async function updatePublisherProject(input: { ownerId: string; projectId: string; name: string; description?: string; visibility: "private" | "public"; manifest?: Partial<KnowledgePackManifest> | null }) { const rows = await getDatabase().update(publisherProjects).set({ name: input.name, description: input.description || null, visibility: input.visibility, ...(input.manifest !== undefined ? { manifest: input.manifest } : {}), updatedAt: new Date() }).where(and(eq(publisherProjects.id, input.projectId), eq(publisherProjects.ownerId, input.ownerId))).returning(); return rows[0]; }
export async function deletePublisherProject(input: { ownerId: string; projectId: string }) {
  const database = getDatabase();
  return database.transaction(async (tx) => {
    const owned = await tx.select({ id: publisherProjects.id }).from(publisherProjects).where(and(eq(publisherProjects.id, input.projectId), eq(publisherProjects.ownerId, input.ownerId))).limit(1);
    if (!owned[0]) return false;
    const releases = await tx.select({ packageId: publisherReleases.packageId, version: publisherReleases.version }).from(publisherReleases).innerJoin(publisherProjects, eq(publisherProjects.id, publisherReleases.projectId)).where(and(eq(publisherReleases.projectId, input.projectId), eq(publisherProjects.ownerId, input.ownerId)));
    for (const release of releases) await tx.delete(registryPacks).where(and(eq(registryPacks.packageId, release.packageId), eq(registryPacks.version, release.version)));
    const deleted = await tx.delete(publisherProjects).where(and(eq(publisherProjects.id, input.projectId), eq(publisherProjects.ownerId, input.ownerId))).returning({ id: publisherProjects.id });
    return Boolean(deleted[0]);
  });
}
export async function listPublisherReleases(ownerId: string) { return getDatabase().select({ id: publisherReleases.id, projectName: publisherProjects.name, publisher: publisherProjects.publisher, packageId: publisherReleases.packageId, version: publisherReleases.version, status: publisherReleases.status, createdAt: publisherReleases.createdAt, distributionStatus: publisherDistributions.status, checksum: publisherDistributions.checksum }).from(publisherReleases).innerJoin(publisherProjects, eq(publisherProjects.id, publisherReleases.projectId)).leftJoin(publisherDistributions, eq(publisherDistributions.releaseId, publisherReleases.id)).where(eq(publisherProjects.ownerId, ownerId)).orderBy(desc(publisherReleases.createdAt)).limit(20); }
export async function listProjectReleases(ownerId: string, projectId: string) { return getDatabase().select({ id: publisherReleases.id, projectName: publisherProjects.name, publisher: publisherProjects.publisher, packageId: publisherReleases.packageId, version: publisherReleases.version, status: publisherReleases.status, createdAt: publisherReleases.createdAt, distributionStatus: publisherDistributions.status, checksum: publisherDistributions.checksum }).from(publisherReleases).innerJoin(publisherProjects, eq(publisherProjects.id, publisherReleases.projectId)).leftJoin(publisherDistributions, eq(publisherDistributions.releaseId, publisherReleases.id)).where(and(eq(publisherProjects.ownerId, ownerId), eq(publisherProjects.id, projectId))).orderBy(desc(publisherReleases.createdAt)).limit(100); }
